classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.ca.salt_master
- system.salt.minion.cert.k8s_server
- system.reclass.storage.salt
#- system.reclass.storage.system.kubernetes_control_cluster
- cluster.mirantis_demo.init_ccp
- cluster.mirantis_demo.init_cicd
parameters:
  _param:
    reclass_data_repository: "https://github.com/mceloud/mcp-demo-salt-model.git"
    reclass_data_revision: fix-ccp
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
    linux_system_codename: xenial

  salt:
    master:
      accept_policy: open_mode
    minion:
      cert:
        k8s_server_cicd:
          host: ${_param:salt_minion_ca_host}
          authority: ${_param:salt_minion_ca_authority}
          common_name: kubernetes-server
          key_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:cicd_cert_location}/kubernetes-server.key
          cert_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:cicd_cert_location}/kubernetes-server.crt
          all_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:cicd_cert_location}/kubernetes-server.pem
          signing_policy: cert_server
          alternative_names: IP:${_param:kubernetes_cicd_control_address},IP:${_param:kubernetes_cicd_control_node01_address},IP:${_param:kubernetes_cicd_control_node02_address},IP:${_param:kubernetes_cicd_control_node03_address},IP:${_param:kubernetes_internal_api_address}
        k8s_server:
          host: ${_param:salt_minion_ca_host}
          authority: ${_param:salt_minion_ca_authority}
          common_name: kubernetes-server
          key_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:ccp_cert_location}/kubernetes-server.key
          cert_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:ccp_cert_location}/kubernetes-server.crt
          all_file: /srv/salt/env/${_param:salt_master_base_environment}/${_param:ccp_cert_location}/kubernetes-server.pem
          signing_policy: cert_server
          alternative_names: IP:${_param:kubernetes_control_address},IP:${_param:kubernetes_control_node01_address},IP:${_param:kubernetes_control_node02_address},IP:${_param:kubernetes_control_node03_address},IP:${_param:kubernetes_internal_api_address}

  reclass:
    storage:
      node:

        # CICD
        kubernetes_cicd_control_node01:
          name: ${_param:kubernetes_cicd_control_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_cicd
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_cicd_control_node01_address}
            keepalived_vip_priority: 103
            data_address: ${_param:kubernetes_cicd_control_node01_data_address}
            deploy_nic: enp3s0f0
            primary_second_nic: enp3s0f1

        kubernetes_cicd_control_node02:
          name: ${_param:kubernetes_cicd_control_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_cicd
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_cicd_control_node02_address}
            keepalived_vip_priority: 102
            data_address: ${_param:kubernetes_cicd_control_node02_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        kubernetes_cicd_control_node03:
          name: ${_param:kubernetes_cicd_control_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_cicd
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_cicd_control_node03_address}
            keepalived_vip_priority: 101
            data_address: ${_param:kubernetes_cicd_control_node03_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        # CCP
        kubernetes_ccp_control_node01:
          name: ${_param:kubernetes_control_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_ccp
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node01_address}
            keepalived_vip_priority: 103
            keepalived_vip_password: password-keepalived-ccp
            data_address: ${_param:kubernetes_control_node01_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        kubernetes_ccp_control_node02:
          name: ${_param:kubernetes_control_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_ccp
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node02_address}
            keepalived_vip_priority: 102
            keepalived_vip_password: password-keepalived-ccp
            data_address: ${_param:kubernetes_control_node02_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        kubernetes_ccp_control_node03:
          name: ${_param:kubernetes_control_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.control_ccp
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_control_node03_address}
            keepalived_vip_priority: 101
            keepalived_vip_password: password-keepalived-ccp
            data_address: ${_param:kubernetes_control_node03_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        kubernetes_compute_node01:
          name: ${_param:kubernetes_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute_ccp
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node01_single_address}
            data_address: ${_param:kubernetes_compute_node01_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1

        kubernetes_compute_node02:
          name: ${_param:kubernetes_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.kubernetes.compute_ccp
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:kubernetes_compute_node02_single_address}
            data_address: ${_param:kubernetes_compute_node02_data_address}
            deploy_nic: eth0
            primary_second_nic: eth1
