classes:
- system.linux.system.repo.docker
- system.linux.system.repo.tcp_base
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client_certificate
#- system.bird.server.single
- cluster.mirantis_int.kubernetes
- cluster.mirantis_int
parameters:
  kubernetes:
    pool:
      network:
        image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/node:latest
        calicoctl:
          image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/ctl:latest
        cni:
          image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/cni:latest

#        volumes:
#          - /srv/calico/bird.cfg.mesh.template:/etc/calico/confd/templates/bird.cfg.mesh.template
#          - /srv/calico/bird.cfg.no-mesh.template:/etc/calico/confd/templates/bird.cfg.no-mesh.template
#          - /srv/calico/custom_filters.cfg:/etc/calico/confd/config/custom_filters.cfg
    common:
      hyperkube:
        image: docker-prod-virtual.docker.mirantis.net/mirantis/kubernetes/hyperkube-amd64:v1.5.1-2
