classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.haproxy.proxy.listen.kubernetes.apiserver_insecure
- system.linux.system.repo.docker
- system.linux.system.repo.tcp_base
- system.kubernetes.master.cluster
- cluster.mirantis_int.kubernetes.compute
- cluster.mirantis_int.kubernetes
- cluster.mirantis_int
parameters:
  _param:
    keepalived_vip_interface: bond0.2402
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": true, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      addons:
        dns:
          replicas: 3
  haproxy:
    proxy:
      listen:
        k8s_secure:
          binds:
          - address: ${_param:k8s_access_vip}
            port: 443
  keepalived:
    cluster:
      instance:
        k8s_access:
          interface: ${_param:deploy_nic}
          virtual_router_id: 90
          priority: ${_param:keepalived_vip_priority}
          password: password
          address: ${_param:k8s_access_vip}
