classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.linux.system.repo.docker
- system.salt.minion.cert.k8s_server_certificate
- system.kubernetes.master.cluster
- cluster.mirantis_demo.kubernetes.compute
- cluster.mirantis_demo
parameters:
  _param:
    keepalived_vip_interface: bond.2408
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": true, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'