classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker
- system.linux.system.repo.tcp_base
- system.kubernetes.master.cluster
- system.glusterfs.server.cluster
- system.glusterfs.client.cluster
- cluster.mirantis_demo.kubernetes.compute_ccp
- cluster.mirantis_demo.kubernetes.init_ccp
- cluster.mirantis_demo.init_ccp
parameters:
  _param:
    keepalived_vip_interface: bond0.2408
    keepalived_vip_virtual_router_id: 70
  kubernetes:
    master:
      cert_source: ${_param:ccp_cert_location}
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": true, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  glusterfs:
    server:
      volumes:
        mcp_data:
          storage: /srv/glusterfs/mcp_data
          replica: 3
          bricks:
            - ${_param:cluster_node01_address}:/srv/glusterfs/mcp_data
            - ${_param:cluster_node02_address}:/srv/glusterfs/mcp_data
            - ${_param:cluster_node03_address}:/srv/glusterfs/mcp_data
          options:
            cluster.readdir-optimize: On
            nfs.disable: On
            network.remote-dio: On
            diagnostics.client-log-level: WARNING
            diagnostics.brick-log-level: WARNING
    client:
      volumes:
        mcp_data:
          path: /srv/volumes/mcp_data
          server: ${_param:cluster_node01_address}
          opts: 'defaults'
  keepalived:
    cluster:
      instance:
        VIP:
          enabled: False
        VIP_ccp:
          address: 10.24.8.20
          interface: bond0.2408
          password: password-ccp
          priority: 101
          virtual_router_id: 70
