classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.linux.system.repo.docker
- system.linux.system.repo.tcp_base
- system.salt.minion.cert.k8s_server_certificate
- system.kubernetes.master.cluster
- system.glusterfs.server.cluster
- system.glusterfs.client.cluster
- cluster.mirantis_demo.kubernetes.compute_cicd
- cluster.mirantis_demo.kubernetes.init_cicd
- cluster.mirantis_demo.init_cicd
parameters:
  _param:
    keepalived_vip_interface: bond0.2408
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": true, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    master:
      addons:
        dns:
          replicas: 3
  glusterfs:
    server:
      volumes:
        mcp_data:
          storage: /srv/glusterfs/mcp_data
          replica: 3
          bricks:
            - ${_param:cluster_node01_address}:/srv/glusterfs/mcp_data
            - ${_param:cluster_node02_address}:/srv/glusterfs/mcp_data
            - ${_param:cluster_node03_address}:/srv/glusterfs/mcp_data
          options:
            cluster.readdir-optimize: On
            nfs.disable: On
            network.remote-dio: On
            diagnostics.client-log-level: WARNING
            diagnostics.brick-log-level: WARNING
    client:
      volumes:
        mcp_data:
          path: /srv/volumes/mcp_data
          server: ${_param:cluster_node01_address}
          opts: 'defaults,use-readdirp=no'
